### ISSUE TITLE
"bazel build webcashd" fails with "error: undefined reference to 'MD5_Init'"

### ISSUE THREAD

**Issue by jokpine** [maaku/webminer#12] opened 2022-05-28 16:59 UTC
```
bazel-out/k8-fastbuild/bin/drogon/lib/libdrogon.a(Utilities.cc.o):Utilities.cc:function drogon::utils::getMd5[abi:cxx11](char const*, unsigned long):
error: undefined reference to 'MD5_Init'

bazel-out/k8-fastbuild/bin/drogon/lib/libdrogon.a(Utilities.cc.o):Utilities.cc:function drogon::utils::getMd5[abi:cxx11](char const*, unsigned long):
error: undefined reference to 'MD5_Update'

bazel-out/k8-fastbuild/bin/drogon/lib/libdrogon.a(Utilities.cc.o):Utilities.cc:function drogon::utils::getMd5[abi:cxx11](char const*, unsigned long):
error: undefined reference to 'MD5_Final'

bazel-out/k8-fastbuild/bin/drogon/lib/libdrogon.a(Utilities.cc.o):Utilities.cc:function drogon::utils::secureRandomBytes(void*, unsigned long):
error: undefined reference to 'RAND_bytes'
```

`libssl-dev` and `openssl` are installed, and I'm able to build drogon using `build.sh` when checking out https://github.com/drogonframework/drogon.

**Comment by maaku** [comment] 2022-05-28 18:46
Can you provide a few more details about your build system? OS, version, etc. bazel builds and links to boringssl instead of using your OS provided libssl.

Sent from my mobile device;
please excuse brevity and any mistakes.

**Comment by maaku** [comment] 2022-05-29 12:12
I'm running on ARM so I had to download and install an arm64 binary from the official GitHub release page for Bazel, as the google apt repository doesn't support arm64 architecture:

```
apt install -y wget
wget https://github.com/bazelbuild/bazel/releases/download/5.1.1/bazel-5.1.1-linux-arm64
chmod +x bazel-5.1.1-linux-arm64
mv bazel-5.1.1-linux-arm64 /usr/local/bin/bazel
```

I was then able to reproduce the issue. I'm not sure at this moment how to solve the problem, but I found a clue:

`ERROR: /webminer/BUILD.bazel:289:6: Foreign Cc - CMake: Building drogon failed: error reading file 'external/drogon/lib/tests/integration_test/server/中文.txt', owner: '@drogon//:lib/tests/integration_test/server/中文.txt': /root/.cache/bazel/_bazel_root/d88ce5de9c2a9a05406f30b02a6818d5/external/drogon/lib/tests/integration_test/server/中文.txt (No such file or directory)`

Looks like it is having trouble reading a Chinese-named file in the drogon sources. Maybe there's a system locale setting that needs to be fixed in this docker image?

**Comment by maaku** [comment] 2022-05-29 12:29
Also you may need to install uuid-dev systemwide. I remember getting bazel to find and use the sandboxed version was an issue when I was building on my Linux machine.

Finally, I should mention that the drogon compilation error we’re encountering here isn’t the link error you mention in the OP. The docker environment doesn’t even get that far yet.

**Comment by maaku** [comment] 2022-05-29 22:24
Able to reproduce the issue now.

**Comment by maaku** [comment] 2022-05-30 01:59
Try now.

**Closed as completed** 2022-05-30 19:16 UTC
